language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build:prod:exclude; fi && npm run build
after_success:
  - npm run report-coverage
  - test $TRAVIS_BRANCH = "master" && npm run generate-docs && npm run deploy-docs
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release
